import jsPDF from 'jspdf';

// ─── Helpers ───────────────────────────────────────────────────────────────

const loadImage = (url) =>
  new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => resolve(img);
    img.onerror = () => resolve(null); // fail silently
    img.src = url;
  });

const toDataURL = (img, w = 300, h = 300) => {
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');

  // Fill background
  ctx.fillStyle = '#1A1A2E';
  ctx.fillRect(0, 0, w, h);

  if (img) {
    // Cover crop
    const ratio = Math.max(w / img.width, h / img.height);
    const nw = img.width * ratio;
    const nh = img.height * ratio;
    const ox = (w - nw) / 2;
    const oy = (h - nh) / 2;
    ctx.drawImage(img, ox, oy, nw, nh);
  } else {
    // Placeholder initial
    ctx.fillStyle = '#C9A84C';
    ctx.font = 'bold 80px serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('?', w / 2, h / 2);
  }

  return canvas.toDataURL('image/jpeg', 0.85);
};

const hex = (color) => color; // passthrough — jsPDF uses hex directly

// ─── Color Palette ─────────────────────────────────────────────────────────
const C = {
  ink:   '#1A1A2E',
  cream: '#F5F0E8',
  gold:  '#C9A84C',
  muted: '#8B8B8B',
  white: '#FFFFFF',
  light: '#F0EBE1',
};

// ─── Main Export Function ───────────────────────────────────────────────────
export const generateYearbookPDF = async (students, onProgress) => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const W = 210; // A4 width mm
  const H = 297; // A4 height mm

  // ── COVER PAGE ────────────────────────────────────────────────────────────
  // Background
  pdf.setFillColor(hex(C.ink));
  pdf.rect(0, 0, W, H, 'F');

  // Gold accent bar
  pdf.setFillColor(hex(C.gold));
  pdf.rect(0, 0, 6, H, 'F');

  // Decorative circle
  pdf.setDrawColor(hex(C.gold));
  pdf.setLineWidth(0.3);
  pdf.circle(W - 40, 60, 50);
  pdf.setLineWidth(0.15);
  pdf.circle(W - 40, 60, 35);

  // Year label
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(hex(C.gold));
  pdf.setCharSpace(4);
  pdf.text('CLASS OF 2025', 20, 80);
  pdf.setCharSpace(0);

  // Title
  pdf.setFont('times', 'bolditalic');
  pdf.setFontSize(52);
  pdf.setTextColor(hex(C.cream));
  pdf.text('Final Year', 20, 110);
  pdf.setTextColor(hex(C.gold));
  pdf.text('Book.', 20, 132);

  // Subtitle
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(hex(C.muted));
  pdf.text('A private yearbook for the graduating class', 20, 150);

  // Student count
  pdf.setFont('times', 'italic');
  pdf.setFontSize(13);
  pdf.setTextColor(hex(C.cream));
  pdf.text(`${students.length} Members`, 20, 168);

  // Bottom line
  pdf.setDrawColor(hex(C.gold));
  pdf.setLineWidth(0.5);
  pdf.line(20, H - 30, W - 20, H - 30);

  // Footer
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(hex(C.muted));
  pdf.text('Generated by FYB · Private & Invite Only', 20, H - 20);
  pdf.text(new Date().toLocaleDateString('en-GB', {
    year: 'numeric', month: 'long'
  }), W - 20, H - 20, { align: 'right' });

  // ── TABLE OF CONTENTS ─────────────────────────────────────────────────────
  pdf.addPage();
  pdf.setFillColor(hex(C.cream));
  pdf.rect(0, 0, W, H, 'F');

  // Gold accent bar
  pdf.setFillColor(hex(C.gold));
  pdf.rect(0, 0, 6, H, 'F');

  // Header
  pdf.setFont('times', 'bolditalic');
  pdf.setFontSize(32);
  pdf.setTextColor(hex(C.ink));
  pdf.text('Contents', 20, 50);

  pdf.setDrawColor(hex(C.gold));
  pdf.setLineWidth(0.5);
  pdf.line(20, 56, W - 20, 56);

  // List students
  pdf.setFont('helvetica', 'normal');
  let tocY = 70;
  const colW = (W - 40) / 2;

  students.forEach((student, i) => {
    const col = i % 2 === 0 ? 0 : 1;
    const row = Math.floor(i / 2);
    const x = 20 + col * colW;
    const y = tocY + row * 10;

    if (y > H - 30) return; // skip overflow

    pdf.setFontSize(9);
    pdf.setTextColor(hex(C.ink));
    pdf.setFont('helvetica', 'bold');
    pdf.text(`${i + 1}.`, x, y);
    pdf.setFont('helvetica', 'normal');
    pdf.text(student.name, x + 6, y);

    pdf.setFontSize(7.5);
    pdf.setTextColor(hex(C.muted));
    pdf.text(student.department || '', x + 6, y + 4);
  });

  // Page number
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(hex(C.muted));
  pdf.text('2', W / 2, H - 15, { align: 'center' });

  // ── STUDENT PAGES ─────────────────────────────────────────────────────────
  const CARDS_PER_PAGE = 4; // 2 columns × 2 rows
  const CARD_W = (W - 50) / 2;  // ~80mm each
  const CARD_H = 105;
  const COLS = 2;
  const ROWS = 2;

  const positions = [
    { x: 15, y: 40  },
    { x: 15 + CARD_W + 20, y: 40  },
    { x: 15, y: 40 + CARD_H + 12 },
    { x: 15 + CARD_W + 20, y: 40 + CARD_H + 12 },
  ];

  let pageNum = 3;

  for (let i = 0; i < students.length; i += CARDS_PER_PAGE) {
    pdf.addPage();
    pdf.setFillColor(hex(C.cream));
    pdf.rect(0, 0, W, H, 'F');

    // Gold sidebar
    pdf.setFillColor(hex(C.gold));
    pdf.rect(0, 0, 6, H, 'F');

    // Page header
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(7);
    pdf.setTextColor(hex(C.muted));
    pdf.setCharSpace(2);
    pdf.text('FINAL YEAR BOOK · CLASS OF 2025', 20, 18);
    pdf.setCharSpace(0);
    pdf.setDrawColor(hex(C.gold));
    pdf.setLineWidth(0.3);
    pdf.line(20, 22, W - 20, 22);

    const batch = students.slice(i, i + CARDS_PER_PAGE);

    for (let j = 0; j < batch.length; j++) {
      const student = batch[j];
      const pos = positions[j];
      const { x, y } = pos;

      onProgress?.(Math.round(((i + j) / students.length) * 100));

      // Load photo
      const img = student.profile_image
        ? await loadImage(student.profile_image)
        : null;
      const dataUrl = toDataURL(img, 200, 200);

      // Card background
      pdf.setFillColor(hex(C.white));
      pdf.roundedRect(x, y, CARD_W, CARD_H, 4, 4, 'F');

      // Card shadow (simulated with border)
      pdf.setDrawColor(230, 225, 215);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(x, y, CARD_W, CARD_H, 4, 4);

      // Photo
      const photoSize = CARD_W - 16;
      pdf.addImage(dataUrl, 'JPEG', x + 8, y + 8, photoSize, photoSize * 0.72);

      // Gold line under photo
      pdf.setFillColor(hex(C.gold));
      pdf.rect(x + 8, y + 8 + photoSize * 0.72, photoSize, 0.8, 'F');

      // Name
      const infoY = y + 8 + photoSize * 0.72 + 7;
      pdf.setFont('times', 'bold');
      pdf.setFontSize(11);
      pdf.setTextColor(hex(C.ink));
      const name = student.name.length > 20
        ? student.name.substring(0, 20) + '…'
        : student.name;
      pdf.text(name, x + 8, infoY);

      // Department
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(7.5);
      pdf.setTextColor(hex(C.gold));
      pdf.text(
        (student.department || 'Department').toUpperCase(),
        x + 8,
        infoY + 5
      );

      // Bio
      if (student.bio) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(7);
        pdf.setTextColor(hex(C.muted));
        const bioLines = pdf.splitTextToSize(student.bio, CARD_W - 16);
        pdf.text(bioLines.slice(0, 2), x + 8, infoY + 11);
      }

      // Card number
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(7);
      pdf.setTextColor(hex(C.muted));
      pdf.text(
        `${i + j + 1}`,
        x + CARD_W - 10,
        y + CARD_H - 5,
        { align: 'right' }
      );
    }

    // Page number
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(8);
    pdf.setTextColor(hex(C.muted));
    pdf.text(`${pageNum}`, W / 2, H - 10, { align: 'center' });
    pageNum++;
  }

  // ── CLOSING PAGE ──────────────────────────────────────────────────────────
  pdf.addPage();
  pdf.setFillColor(hex(C.ink));
  pdf.rect(0, 0, W, H, 'F');

  pdf.setFillColor(hex(C.gold));
  pdf.rect(0, 0, 6, H, 'F');

  // Circle decoration
  pdf.setDrawColor(hex(C.gold));
  pdf.setLineWidth(0.3);
  pdf.circle(40, H - 50, 40);
  pdf.setLineWidth(0.15);
  pdf.circle(40, H - 50, 25);

  pdf.setFont('times', 'bolditalic');
  pdf.setFontSize(36);
  pdf.setTextColor(hex(C.cream));
  pdf.text('The End.', W / 2, H / 2 - 10, { align: 'center' });

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.setTextColor(hex(C.muted));
  pdf.text(
    'Thank you for the memories.',
    W / 2, H / 2 + 8,
    { align: 'center' }
  );

  pdf.setDrawColor(hex(C.gold));
  pdf.setLineWidth(0.5);
  pdf.line(W / 2 - 30, H / 2 + 16, W / 2 + 30, H / 2 + 16);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8);
  pdf.setTextColor(hex(C.muted));
  pdf.text('FYB · Class of 2025', W / 2, H - 20, { align: 'center' });

  // ── SAVE ──────────────────────────────────────────────────────────────────
  pdf.save('FYB-Yearbook-2025.pdf');
};